#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
publish_gps_zenoh.py
====================
Bridge synapse FlatBuffers pose/odometry from Zenoh onto the vehicle as a GNSS
fix over the SiK telemetry radio.

``publish_gps_synapse.py`` takes its input from ROS 2 (``nav_msgs/Odometry``).
This one takes it from the synapse wire format itself: the fixed-layout payload
structs that https://github.com/CogniPilot/synapse_fbs defines and that a mocap
bridge publishes on Zenoh under ``[<namespace>/]<key>[/<instance>]``.

What goes *out* is unchanged -- the same bare 64-byte ``GnssFixData`` in the
same compact serial framing -- so the vehicle side, the ``-S mocap-gnss``
requirement and the calibrated ``origin_*`` / ``yaw_offset`` values all carry
over unchanged from the ROS script.

Input topics (``--topic``), all named by their synapse catalog key:

    external_pose  ExternalOdometryData  the estimator-input contract a mocap
                                         bridge writes into the vehicle's
                                         namespace; carries velocity and a
                                         tracking status. The default.
    odom           OdometryData          a filtered estimate, same content
    pose           PoseData              filtered pose, no velocity
    pose_raw       RawPoseData           unfiltered source pose, no velocity
    mocap          MocapPoseFrame        raw mocap frame; --instance selects
                                         which rigid body

There is no ``frame`` parameter here, unlike the ROS script. The synapse types
name their frame in the field itself (``position_enu_m``,
``angular_velocity_flu_rad_s``), and the README requires bridges to transform
before publishing, so the input is ENU by contract and cannot be FLU.

Usage
-----
    ./publish_gps_zenoh.py --port /dev/ttyUSB0
    ./publish_gps_zenoh.py --port /dev/ttyUSB0 --namespace cub1 --instance 0
    ./publish_gps_zenoh.py --topic mocap --instance 7 --dry-run
    ./publish_gps_zenoh.py --simulate --dry-run     # no mocap and no radio
    ./publish_gps_zenoh.py --selftest               # no zenoh needed
    ./publish_gps_zenoh.py --list-topics

Requirements
------------
    pip install eclipse-zenoh synapse-fbs pyserial

Check it landed, on the vehicle shell:

    csyn topic echo gnss
    csyn_serial status
"""

from __future__ import annotations

import argparse
import math
import struct
import sys
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Optional, Tuple

_HERE = Path(__file__).resolve().parent

# The serial wire format lives with the ground tool; never duplicate it here,
# or the two ends can silently drift apart.
sys.path.insert(0, str(_HERE.parent / "tools" / "synapse_serial"))
try:
    from synapse_serial import FrameDecoder, TOPIC_GNSS_FIX, TOPIC_NAMES, encode_frame
except ImportError as exc:  # pragma: no cover - a broken checkout, not a runtime path
    sys.exit(f"ERROR: cannot import the synapse wire format: {exc}")

# The geodetic math and the calibration constants live with the ROS script for
# the same reason: an origin and a yaw_offset trimmed against one bridge have
# to mean the same thing in the other. That module guards its rclpy import, so
# importing it here does not require a sourced ROS workspace.
sys.path.insert(0, str(_HERE))
try:
    from publish_gps_synapse import build_gnss_fix, quaternion_to_yaw, rotate_2d
except ImportError as exc:  # pragma: no cover
    sys.exit(f"ERROR: cannot import the shared conversion from publish_gps_synapse.py: {exc}")


# ──────────────────────────────────────────────────────────────────────────────
# synapse_fbs bindings
# ──────────────────────────────────────────────────────────────────────────────
# Decoding goes through the published bindings rather than hand-written struct
# formats, so the field offsets and every enum value come from the schema
# itself. --selftest pins that decoder against a reference buffer generated by
# flatc, which is the only thing here that could not be checked by inspection.
try:
    from synapse import topic_catalog
    from synapse.topic.ExternalOdometryCovarianceData import ExternalOdometryCovarianceData
    from synapse.topic.ExternalOdometryData import ExternalOdometryData
    from synapse.topic.ExternalOdometryFlags import ExternalOdometryFlags
    from synapse.topic.ExternalOdometryStatus import ExternalOdometryStatus
    from synapse.topic.MocapPoseFrame import MocapPoseFrame
    from synapse.topic.MocapRawFlags import MocapRawFlags
    from synapse.topic.OdometryData import OdometryData
    from synapse.topic.PoseData import PoseData
    from synapse.topic.RawPoseData import RawPoseData
    from synapse.types.CovarianceUpperTriangle78f import CovarianceUpperTriangle78f
    from synapse.types.GnssFixType import GnssFixType
    from synapse.types.Posef import Posef
    from synapse.types.Quaternionf import Quaternionf
    from synapse.types.Twistf import Twistf
    from synapse.types.Vec3f import Vec3f
    HAVE_SYNAPSE_FBS = True
except ImportError:
    HAVE_SYNAPSE_FBS = False

# The firmware pins synapse_fbs 0.7.0; the Python package is versioned
# separately and is 0.8.0 at the time of writing. What has to agree is not the
# release number but the schema set, so that is what gets checked. A mismatch
# here is the same fault the vehicle reports as a climbing bad_len counter,
# caught before anything reaches the radio.
FIRMWARE_SCHEMA_SET_HASH = "2fd857effb6c7558d6869f4307a5354c"

# Accuracy fields saturate at 65535 mm, which the schema documents as "at or
# above 65.535 m, unusable". That is the honest value to send while tracking is
# lost, and it is the receiver-native way to say so.
ACCURACY_UNUSABLE_M = 65.535


# ──────────────────────────────────────────────────────────────────────────────
# Normalised sample
# ──────────────────────────────────────────────────────────────────────────────
@dataclass
class PoseSample:
    """One decoded input sample, reduced to what a GNSS fix can carry."""

    timestamp_us: int
    east: float
    north: float
    up: float
    quat: Optional[Tuple[float, float, float, float]] = None      # w, x, y, z
    velocity_enu: Optional[Tuple[float, float, float]] = None     # ve, vn, vu
    lost: bool = False
    degraded: bool = False
    status: str = ""


def _enum_names(cls) -> dict:
    return {v: k for k, v in vars(cls).items() if not k.startswith("_")}


def _status_name(cls, value: int) -> str:
    return _enum_names(cls).get(value, f"status{value}")


FIX_TYPE_NAMES = _enum_names(GnssFixType) if HAVE_SYNAPSE_FBS else {}


# ExternalOdometryFlags and OdometryFlags declare the same eight bits in the
# same order, and ExternalOdometryStatus and OdometryStatus the same seven
# values, so one set of helpers covers both families. --selftest does not check
# that, because a divergence would be a schema change: the sizes and the schema
# set hash it does check would move with it.
def _flags_lost(flags: int) -> bool:
    return bool(flags & ExternalOdometryFlags.Lost)


def _flags_degraded(flags: int) -> bool:
    return bool(flags & (ExternalOdometryFlags.Extrapolated
                         | ExternalOdometryFlags.OutlierRejected
                         | ExternalOdometryFlags.Degraded))


def _status_lost(status: int) -> bool:
    return status == ExternalOdometryStatus.Lost


def _status_degraded(status: int) -> bool:
    return status in (ExternalOdometryStatus.ExtrapolatedShort,
                      ExternalOdometryStatus.ExtrapolatedLong,
                      ExternalOdometryStatus.OutlierRejected,
                      ExternalOdometryStatus.Degraded)


# ──────────────────────────────────────────────────────────────────────────────
# Decoders, one per input topic
# ──────────────────────────────────────────────────────────────────────────────
def _decode_external_pose(payload: bytes, instance: Optional[int],
                          ignore_flags: bool = False) -> Optional[PoseSample]:
    data = ExternalOdometryData()
    data.Init(bytearray(payload), 0)
    if instance is not None and data.Id() != instance:
        return None

    flags = data.Flags()
    if not flags & ExternalOdometryFlags.PositionValid and not ignore_flags:
        return None

    pos = data.PositionEnuM(Vec3f())
    sample = PoseSample(
        timestamp_us=data.TimestampUs(),
        east=pos.X(), north=pos.Y(), up=pos.Z(),
        lost=_flags_lost(flags) or _status_lost(data.Status()),
        degraded=_flags_degraded(flags) or _status_degraded(data.Status()),
        status=_status_name(ExternalOdometryStatus, data.Status()),
    )
    if flags & ExternalOdometryFlags.AttitudeValid or ignore_flags:
        q = data.Attitude(Quaternionf())
        sample.quat = (q.W(), q.X(), q.Y(), q.Z())
    if flags & ExternalOdometryFlags.LinearVelocityValid or ignore_flags:
        v = data.LinearVelocityEnuMS(Vec3f())
        sample.velocity_enu = (v.X(), v.Y(), v.Z())
    return sample


def _decode_odom(payload: bytes, instance: Optional[int],
                 ignore_flags: bool = False) -> Optional[PoseSample]:
    del instance  # OdometryData is single-instance; the key carries no id.
    data = OdometryData()
    data.Init(bytearray(payload), 0)

    flags = data.Flags()
    if not flags & ExternalOdometryFlags.PositionValid and not ignore_flags:
        return None

    pose = data.Pose(Posef())
    pos = pose.PositionEnuM(Vec3f())
    sample = PoseSample(
        timestamp_us=data.TimestampUs(),
        east=pos.X(), north=pos.Y(), up=pos.Z(),
        lost=_flags_lost(flags) or _status_lost(data.Status()),
        degraded=_flags_degraded(flags) or _status_degraded(data.Status()),
        status=_status_name(ExternalOdometryStatus, data.Status()),
    )
    if flags & ExternalOdometryFlags.AttitudeValid or ignore_flags:
        q = pose.Attitude(Quaternionf())
        sample.quat = (q.W(), q.X(), q.Y(), q.Z())
    if flags & ExternalOdometryFlags.LinearVelocityValid or ignore_flags:
        v = data.Twist(Twistf()).LinearVelocityEnuMS(Vec3f())
        sample.velocity_enu = (v.X(), v.Y(), v.Z())
    return sample


def _decode_pose_like(cls):
    """PoseData and RawPoseData differ only in name: timestamp plus a Posef."""

    def decode(payload: bytes, instance: Optional[int],
               ignore_flags: bool = False) -> Optional[PoseSample]:
        del instance, ignore_flags  # neither type carries validity bits
        data = cls()
        data.Init(bytearray(payload), 0)
        pose = data.Pose(Posef())
        pos = pose.PositionEnuM(Vec3f())
        q = pose.Attitude(Quaternionf())
        # Neither type carries validity bits, so there is nothing to gate on:
        # a sample on the topic is the producer asserting the pose is good.
        return PoseSample(
            timestamp_us=data.TimestampUs(),
            east=pos.X(), north=pos.Y(), up=pos.Z(),
            quat=(q.W(), q.X(), q.Y(), q.Z()),
        )

    return decode


def _decode_mocap(payload: bytes, instance: Optional[int],
                  ignore_flags: bool = False) -> Optional[PoseSample]:
    """Pick one rigid body out of a raw mocap frame.

    mocap.fbs calls MocapPoseFrame a debugging and bridge-level type and points
    estimators at ExternalOdometry instead, so this path exists for the case
    where no bridge is running yet and the mocap source is all there is.
    """
    frame = MocapPoseFrame.GetRootAs(bytearray(payload), 0)
    count = frame.RigidBodiesLength()
    if count == 0:
        return None

    body = None
    if instance is None:
        body = frame.RigidBodies(0)
    else:
        for i in range(count):
            candidate = frame.RigidBodies(i)
            if candidate.Id() == instance:
                body = candidate
                break
    if body is None:
        return None
    if not body.Flags() & MocapRawFlags.Valid and not ignore_flags:
        return None

    pose = body.Pose(Posef())
    pos = pose.PositionEnuM(Vec3f())
    q = pose.Attitude(Quaternionf())
    return PoseSample(
        timestamp_us=frame.TimestampUs(),
        east=pos.X(), north=pos.Y(), up=pos.Z(),
        quat=(q.W(), q.X(), q.Y(), q.Z()),
        status=f"rigid_body{body.Id()}",
    )


@dataclass(frozen=True)
class InputTopic:
    key: str
    decode: Callable[[bytes, Optional[int]], Optional[PoseSample]]
    note: str


def input_topics() -> dict:
    return {
        "external_pose": InputTopic("external_pose", _decode_external_pose,
                                    "estimator input from a mocap bridge"),
        "odom": InputTopic("odom", _decode_odom, "filtered estimate"),
        "pose": InputTopic("pose", _decode_pose_like(PoseData), "filtered pose, no velocity"),
        "pose_raw": InputTopic("pose_raw", _decode_pose_like(RawPoseData),
                               "unfiltered source pose, no velocity"),
        "mocap": InputTopic("mocap", _decode_mocap, "raw mocap frame, --instance picks a body"),
    }


# ──────────────────────────────────────────────────────────────────────────────
# Optional accuracy from the covariance companion topic
# ──────────────────────────────────────────────────────────────────────────────
# ExternalOdometryCovarianceData holds the upper triangle of the 12D tangent
# state [theta, velocity, position, angular_velocity], row-major. Row i of an
# n=12 upper triangle starts at i*n - i*(i-1)/2, and position is rows 6..8, so
# the three position variances are elements 57, 63 and 68.
_COV_N = 12


def _tri_diag(i: int, n: int = _COV_N) -> int:
    return i * n - i * (i - 1) // 2


COV_IDX_EAST = _tri_diag(6)
COV_IDX_NORTH = _tri_diag(7)
COV_IDX_UP = _tri_diag(8)


def decode_covariance(payload: bytes, instance: Optional[int]):
    """Return (timestamp_us, h_acc_m, v_acc_m) or None."""
    data = ExternalOdometryCovarianceData()
    data.Init(bytearray(payload), 0)
    if instance is not None and data.Id() != instance:
        return None

    cov = data.Covariance(CovarianceUpperTriangle78f())
    var_e = getattr(cov, f"C{COV_IDX_EAST}")()
    var_n = getattr(cov, f"C{COV_IDX_NORTH}")()
    var_u = getattr(cov, f"C{COV_IDX_UP}")()
    if var_e < 0.0 or var_n < 0.0 or var_u < 0.0:
        return None
    return data.TimestampUs(), math.sqrt(var_e + var_n), math.sqrt(var_u)


# ──────────────────────────────────────────────────────────────────────────────
# Sample -> GnssFix
# ──────────────────────────────────────────────────────────────────────────────
def sample_to_fix(sample: PoseSample, prev, args, boot_us: float, accuracy=None):
    """Convert one PoseSample into a GnssFix.

    ``prev`` is (east, north, up, monotonic) from the previous send, used only
    to difference a velocity when the input carries none. Returns
    (fix, east, north, up, vn, ve, vd, yaw_deg).
    """
    east, north, up = sample.east, sample.north, sample.up

    # Rotate the facility frame onto true north. Identical to the ROS script,
    # so a yaw_offset trimmed there is still correct here.
    if args.yaw_offset != 0.0:
        east, north = rotate_2d(east, north, args.yaw_offset)

    have_velocity = False
    ve = vn = vd = 0.0
    if sample.velocity_enu is not None:
        ve, vn, vu = sample.velocity_enu
        # Velocity lives in the same facility frame as position, so it takes
        # the same rotation. The ROS script gets this for free by differencing
        # already-rotated positions.
        if args.yaw_offset != 0.0:
            ve, vn = rotate_2d(ve, vn, args.yaw_offset)
        vd = -vu
        have_velocity = True
    elif prev is not None:
        dt = time.monotonic() - prev[3]
        if dt > 0.001:
            ve = (east - prev[0]) / dt
            vn = (north - prev[1]) / dt
            vd = -(up - prev[2]) / dt
            have_velocity = True

    yaw_deg = None
    if sample.quat is not None:
        w, x, y, z = sample.quat
        yaw_deg = (quaternion_to_yaw(x, y, z, w) + args.heading_offset) % 360.0

    if sample.lost:
        fix_type = GnssFixType.NoFix
        h_acc, v_acc = ACCURACY_UNUSABLE_M, ACCURACY_UNUSABLE_M
    else:
        fix_type = GnssFixType.Fix3d
        if accuracy is not None:
            h_acc, v_acc = accuracy
        else:
            h_acc, v_acc = args.hacc, args.vacc
        if sample.degraded:
            h_acc *= args.degraded_scale
            v_acc *= args.degraded_scale

    fix = build_gnss_fix(
        east, north, up, vn, ve, vd,
        args.origin_lat, args.origin_lon, args.origin_alt,
        boot_us=boot_us,
        yaw_deg=yaw_deg if args.publish_yaw else None,
        hdop=args.hdop, vdop=args.vdop, satellites=args.satellites,
        fix_type=fix_type, h_acc_m=h_acc, v_acc_m=v_acc,
        instance=args.gnss_instance, have_velocity=have_velocity,
    )
    return fix, east, north, up, vn, ve, vd, yaw_deg


# ──────────────────────────────────────────────────────────────────────────────
# Bridge
# ──────────────────────────────────────────────────────────────────────────────
class Bridge:
    def __init__(self, args):
        self.args = args
        self.topic = input_topics()[args.topic]
        self.lock = threading.Lock()
        self.sample = None
        self.sample_at = 0.0
        self.accuracy = None
        self.accuracy_at = 0.0
        self.decode_errors = 0
        self.arrived = 0
        self.dropped = 0
        self.last_arrival = None
        self.received = 0
        self.sent = 0
        self.seq = 0
        self.matched_key = None
        self.start = time.monotonic()
        self.prev = None
        self.link = None
        self.decoder = FrameDecoder()
        self.from_vehicle = {}
        self.read_error_logged = False

        if not args.dry_run:
            self._open_serial()

    # ── serial ───────────────────────────────────────────────────────────────
    def _open_serial(self):
        try:
            import serial
        except ImportError:
            sys.exit("pyserial is required unless --dry-run: pip install pyserial")
        try:
            self.link = serial.Serial(self.args.port, self.args.baud, timeout=0)
        except Exception as exc:
            sys.exit(f"cannot open {self.args.port}: {exc}")
        print(f"radio: {self.args.port} @ {self.args.baud}")

    # ── zenoh callbacks ──────────────────────────────────────────────────────
    def on_sample(self, sample):
        payload = _payload_bytes(sample)
        # Counted before the decode, so a topic that arrives but is rejected
        # can be told apart from one that never arrives at all. Those two look
        # identical from the outside and have nothing in common as faults.
        with self.lock:
            self.arrived += 1
            self.last_arrival = (str(sample.key_expr), len(payload))
        try:
            decoded = self.topic.decode(payload, self.args.instance, self.args.ignore_flags)
        except Exception as exc:
            self.decode_errors += 1
            if self.decode_errors == 1:
                print(f"decode failed on {sample.key_expr} ({len(payload)} B): {exc}",
                      file=sys.stderr)
            return
        if decoded is None:
            with self.lock:
                self.dropped += 1
            return
        with self.lock:
            self.sample = decoded
            self.sample_at = time.monotonic()
            self.received += 1
            self.matched_key = str(sample.key_expr)

    def on_covariance(self, sample):
        try:
            decoded = decode_covariance(_payload_bytes(sample), self.args.instance)
        except Exception:
            return
        if decoded is None:
            return
        with self.lock:
            self.accuracy = (decoded[1], decoded[2])
            self.accuracy_at = time.monotonic()

    def offer(self, decoded: PoseSample):
        """Inject a sample directly, for --simulate."""
        with self.lock:
            self.sample = decoded
            self.sample_at = time.monotonic()
            self.received += 1
            self.matched_key = "(simulated)"

    # ── periodic send ────────────────────────────────────────────────────────
    def tick(self):
        self._drain_vehicle()
        now = time.monotonic()

        with self.lock:
            sample = self.sample
            age = now - self.sample_at
            accuracy = self.accuracy if now - self.accuracy_at < self.args.timeout else None
            key = self.matched_key

        if sample is None:
            return None
        if age > self.args.timeout:
            # A frozen position sent at full confidence is worse than no fix at
            # all: the estimator has no way to tell it is stale. Say so instead.
            sample = PoseSample(sample.timestamp_us, sample.east, sample.north, sample.up,
                                lost=True, status=f"stale {age:.1f}s")
            accuracy = None

        boot_us = (now - self.start) * 1e6
        fix, east, north, up, vn, ve, vd, yaw = sample_to_fix(
            sample, self.prev, self.args, boot_us, accuracy)
        self.prev = (east, north, up, now)

        if self.link is not None:
            try:
                self.link.write(encode_frame(TOPIC_GNSS_FIX, fix.pack(), self.seq))
            except Exception as exc:
                print(f"serial write failed: {exc}", file=sys.stderr)
        self.seq = (self.seq + 1) & 0xFF
        self.sent += 1
        return sample, fix, east, north, up, vn, ve, vd, yaw, key

    def _drain_vehicle(self):
        if self.link is None:
            return
        try:
            waiting = self.link.in_waiting
            if not waiting:
                return
            for topic_id, _seq, _payload in self.decoder.feed(self.link.read(waiting)):
                name = TOPIC_NAMES.get(topic_id, f"id{topic_id}")
                self.from_vehicle[name] = self.from_vehicle.get(name, 0) + 1
        except Exception as exc:
            if not self.read_error_logged:
                print(f"serial read failed: {exc}", file=sys.stderr)
                self.read_error_logged = True

    def waiting_line(self, key: str) -> str:
        with self.lock:
            arrived, dropped, last = self.arrived, self.dropped, self.last_arrival
        if arrived == 0:
            return (f"nothing arriving on {key} -- check --connect and the key; "
                    "zenoh_scan.py lists what is actually publishing")
        return (f"{arrived} samples on {last[0]} ({last[1]} B), all {dropped} rejected: "
                "validity flags clear, or filtered out by --instance. "
                "--ignore-flags accepts them regardless.")

    def status_line(self, result) -> str:
        sample, fix, east, north, up, vn, ve, vd, yaw, key = result
        back = ", ".join(f"{k}={v}" for k, v in sorted(self.from_vehicle.items()))
        return (
            f"E={east:+7.3f} N={north:+7.3f} U={up:+6.3f} | "
            f"vn={vn:+6.3f} ve={ve:+6.3f} vd={vd:+6.3f} | "
            f"lat={fix.latitude_deg_e7 / 1e7:.7f} lon={fix.longitude_deg_e7 / 1e7:.7f} "
            f"alt={fix.altitude_msl_mm / 1000.0:.2f} | "
            f"yaw={'--' if yaw is None else format(yaw, '.1f')} | "
            f"{sample.status or 'ok'} hacc={fix.horizontal_accuracy_mm / 1000.0:.2f}m "
            f"fix={FIX_TYPE_NAMES.get(fix.fix_type, fix.fix_type)} | "
            f"rx={self.received} tx={self.sent} on {key} | "
            f"from vehicle: {back or 'nothing yet'}"
        )


def _payload_bytes(sample) -> bytes:
    """zenoh-python returned bytes before 1.0 and a ZBytes after it."""
    payload = sample.payload
    if isinstance(payload, (bytes, bytearray)):
        return bytes(payload)
    to_bytes = getattr(payload, "to_bytes", None)
    return to_bytes() if callable(to_bytes) else bytes(payload)


# ──────────────────────────────────────────────────────────────────────────────
# Key construction
# ──────────────────────────────────────────────────────────────────────────────
def resolve_mode(mode: Optional[str], connect: Optional[str]) -> str:
    """Connecting to a known router is the textbook client-mode case; peer mode
    is for discovering whatever is on the local network."""
    return mode or ("client" if connect else "peer")


def zenoh_config(zenoh, connect: Optional[str], mode: str):
    config = zenoh.Config()
    config.insert_json5("mode", f'"{mode}"')
    if connect:
        config.insert_json5("connect/endpoints", f'["{connect}"]')
    return config


def build_key(args) -> str:
    if args.key:
        return args.key
    info = topic_catalog.topic_by_key(args.topic)
    parts = []
    if args.namespace:
        parts.append(args.namespace)
    parts.append(info.key)
    if info.multi_instance:
        # ** rather than * so a publisher that omits the instance segment
        # entirely still matches; the id inside the payload is what --instance
        # actually filters on.
        parts.append("**")
    return "/".join(parts)


# ──────────────────────────────────────────────────────────────────────────────
# Simulation source, so the whole chain can be exercised with no mocap
# ──────────────────────────────────────────────────────────────────────────────
# Only used to *produce* bytes; everything downstream decodes them through the
# synapse_fbs bindings like a real sample. --selftest checks this round trip,
# which is what keeps this hand-written layout honest.
SIM_EXTERNAL_ODOMETRY = struct.Struct("<Q3f4f3f3f4B")


def simulate_payload(t: float, radius: float, period: float, instance: int,
                     flags: Optional[int] = None, status: Optional[int] = None) -> bytes:
    angle = 2.0 * math.pi * (t / period)
    east, north, up = radius * math.cos(angle), radius * math.sin(angle), 1.5
    speed = 2.0 * math.pi * radius / period
    ve, vn, vu = -speed * math.sin(angle), speed * math.cos(angle), 0.0
    yaw = angle + math.pi / 2.0
    if flags is None:
        flags = (ExternalOdometryFlags.PositionValid | ExternalOdometryFlags.AttitudeValid
                 | ExternalOdometryFlags.LinearVelocityValid)
    if status is None:
        status = ExternalOdometryStatus.Filtered
    return SIM_EXTERNAL_ODOMETRY.pack(
        int(t * 1e6), east, north, up,
        math.cos(yaw / 2.0), 0.0, 0.0, math.sin(yaw / 2.0),
        ve, vn, vu, 0.0, 0.0, 2.0 * math.pi / period,
        flags, status, 0, instance)


# ──────────────────────────────────────────────────────────────────────────────
# Selftest
# ──────────────────────────────────────────────────────────────────────────────
# The inline ExternalOdometryData from a buffer flatc built out of
# fbs/state.fbs. Distinctive values, all exactly representable as float32.
REFERENCE_EXTERNAL_POSE = bytes.fromhex(
    "cb04fb711f0100000000c03f000010c0"
    "000048400000003f0000803e000000be"
    "0000803d00002841000034c100004241"
    "0000403f000000bf0000803e07012a03"
)
REFERENCE_VALUES = dict(
    timestamp_us=1234567890123,
    position=(1.5, -2.25, 3.125),
    quat=(0.5, 0.25, -0.125, 0.0625),
    velocity=(10.5, -11.25, 12.125),
    flags=7, status=1, source_id=42, id=3,
)


def cmd_selftest() -> int:
    failures = 0

    def check(label, got, want):
        nonlocal failures
        ok = got == want
        failures += not ok
        print(f"{'ok  ' if ok else 'FAIL'} {label}")
        if not ok:
            print(f"      got  {got}\n      want {want}")

    check("schema set hash matches the firmware pin",
          topic_catalog.SCHEMA_SET_HASH, FIRMWARE_SCHEMA_SET_HASH)

    for key, size in (("external_pose", 64), ("odom", 72), ("pose", 40),
                      ("pose_raw", 40), ("external_pose_cov", 328)):
        check(f"{key} payload size", topic_catalog.topic_by_key(key).payload_size, size)

    # The decoder, against a buffer this script did not produce.
    sample = _decode_external_pose(REFERENCE_EXTERNAL_POSE, None)
    check("reference buffer decodes", sample is not None, True)
    if sample is not None:
        check("reference timestamp", sample.timestamp_us, REFERENCE_VALUES["timestamp_us"])
        check("reference position", (sample.east, sample.north, sample.up),
              REFERENCE_VALUES["position"])
        check("reference attitude", sample.quat, REFERENCE_VALUES["quat"])
        check("reference velocity", sample.velocity_enu, REFERENCE_VALUES["velocity"])
        check("reference not lost or degraded", (sample.lost, sample.degraded), (False, False))

    check("reference instance filter rejects a mismatch",
          _decode_external_pose(REFERENCE_EXTERNAL_POSE, 99), None)
    check("reference instance filter accepts a match",
          _decode_external_pose(REFERENCE_EXTERNAL_POSE, 3) is not None, True)

    # The simulation packer, round-tripped through the schema decoder. If the
    # hand-written format string above were wrong, this is what would catch it.
    check("simulated payload is one payload_size", SIM_EXTERNAL_ODOMETRY.size, 64)
    sim = _decode_external_pose(simulate_payload(0.0, 4.0, 20.0, 5), 5)
    check("simulated payload decodes", sim is not None, True)
    if sim is not None:
        check("simulated position", (round(sim.east, 4), round(sim.north, 4), round(sim.up, 4)),
              (4.0, 0.0, 1.5))
        check("simulated velocity is tangential",
              round(sim.velocity_enu[0], 4) == 0.0 and sim.velocity_enu[1] > 0.0, True)

    # A producer that keeps publishing a position while reporting Lost has to
    # survive decoding as a sample, not be dropped: dropping it would leave the
    # downgrade to the staleness timeout instead of taking effect at once.
    lost_wire = _decode_external_pose(
        simulate_payload(0.0, 4.0, 20.0, 0,
                         flags=ExternalOdometryFlags.PositionValid | ExternalOdometryFlags.Lost,
                         status=ExternalOdometryStatus.Lost), None)
    check("a Lost producer sample decodes as lost",
          lost_wire is not None and lost_wire.lost, True)

    # Covariance indexing, checked against a direct enumeration of the triangle.
    rows, idx = [], 0
    for i in range(_COV_N):
        rows.append(idx)
        idx += _COV_N - i
    check("upper triangle has 78 elements", idx, 78)
    check("position variance indices", (COV_IDX_EAST, COV_IDX_NORTH, COV_IDX_UP),
          (rows[6], rows[7], rows[8]))

    # End to end: a sample becomes a frame the ground decoder accepts back.
    args = argparse.Namespace(
        yaw_offset=0.0, heading_offset=0.0, publish_yaw=False, origin_lat=40.0,
        origin_lon=-86.0, origin_alt=0.0, hdop=0.3, vdop=0.4, satellites=14,
        hacc=0.05, vacc=0.08, degraded_scale=4.0, gnss_instance=0)
    fix, *_ = sample_to_fix(sample, None, args, 0.0)
    check("fix from reference sample is 3d", fix.fix_type, GnssFixType.Fix3d)
    frames = FrameDecoder().feed(encode_frame(TOPIC_GNSS_FIX, fix.pack(), 7))
    check("round trip through the serial framing",
          [(t, s, len(p)) for t, s, p in frames], [(TOPIC_GNSS_FIX, 7, 64)])

    lost = PoseSample(0, 1.0, 2.0, 3.0, lost=True)
    lost_fix, *_ = sample_to_fix(lost, None, args, 0.0)
    check("a lost sample reports NoFix", lost_fix.fix_type, GnssFixType.NoFix)
    check("a lost sample saturates accuracy", lost_fix.horizontal_accuracy_mm, 65535)

    degraded = PoseSample(0, 1.0, 2.0, 3.0, degraded=True)
    deg_fix, *_ = sample_to_fix(degraded, None, args, 0.0)
    check("a degraded sample inflates accuracy",
          deg_fix.horizontal_accuracy_mm, int(round(args.hacc * 4.0 * 1000)))

    print("FAILED" if failures else "all checks passed")
    return 1 if failures else 0


# ──────────────────────────────────────────────────────────────────────────────
# Run modes
# ──────────────────────────────────────────────────────────────────────────────
def cmd_list_topics() -> int:
    print(f"schema set {topic_catalog.SCHEMA_SET_HASH}")
    print(f"{'--topic':<16}{'id':>4}  {'payload':<32}{'size':>6}  note")
    for name, topic in input_topics().items():
        info = topic_catalog.topic_by_key(topic.key)
        size = info.payload_size if info.payload_size else "table"
        print(f"{name:<16}{info.id:>4}  {str(info.payload_type or info.root_table):<32}"
              f"{str(size):>6}  {topic.note}")
    return 0


def run(args) -> int:
    zenoh = None
    if not args.simulate:
        try:
            import zenoh  # noqa: F811  - checked before the serial port is opened
        except ImportError:
            return _die("eclipse-zenoh is required unless --simulate: pip install eclipse-zenoh")

    bridge = Bridge(args)
    period = 1.0 / args.rate
    session = None
    # Undeclared on garbage collection, so the handles have to outlive this
    # scope's setup block or the subscription silently stops delivering.
    subscribers = []

    if args.simulate:
        print("simulating a circular trajectory; no zenoh session")
    else:
        mode = resolve_mode(args.mode, args.connect)
        try:
            session = zenoh.open(zenoh_config(zenoh, args.connect, mode))
        except Exception as exc:
            return _die(f"cannot open a zenoh session in {mode} mode:\n  {exc}\n"
                        "       zenoh_scan.py reports what is reachable and what "
                        "is publishing.")

        key = build_key(args)
        subscribers.append(session.declare_subscriber(key, bridge.on_sample))
        print(f"subscribed to {key}")
        if args.covariance and args.topic == "external_pose":
            cov_key = build_key(argparse.Namespace(
                key=None, namespace=args.namespace, topic="external_pose_cov"))
            subscribers.append(session.declare_subscriber(cov_key, bridge.on_covariance))
            print(f"subscribed to {cov_key} for accuracy")

    print(f"origin {args.origin_lat:.7f} {args.origin_lon:.7f} alt={args.origin_alt:.1f} | "
          f"{args.rate} Hz | yaw_offset={args.yaw_offset:.1f}")

    last_log = time.monotonic()
    next_send = time.monotonic()
    try:
        while True:
            if args.simulate:
                t = time.monotonic() - bridge.start
                decoded = bridge.topic.decode(
                    simulate_payload(t, args.sim_radius, args.sim_period, args.instance or 0),
                    args.instance)
                if decoded is not None:
                    bridge.offer(decoded)

            result = bridge.tick()
            now = time.monotonic()
            if now - last_log >= 1.0:
                print(bridge.status_line(result) if result else
                      bridge.waiting_line(build_key(args)))
                last_log = now

            next_send += period
            # A long stall must not turn into a burst of catch-up frames.
            if next_send < now:
                next_send = now + period
            time.sleep(max(0.0, next_send - time.monotonic()))
    except KeyboardInterrupt:
        print()
    finally:
        subscribers.clear()
        if session is not None:
            session.close()

    print(f"received {bridge.received}, sent {bridge.sent}, "
          f"decode errors {bridge.decode_errors}")
    if bridge.from_vehicle:
        print("from vehicle: " + ", ".join(f"{k}={v}" for k, v in sorted(bridge.from_vehicle.items())))
    return 0


def _die(message: str) -> int:
    print(f"ERROR: {message}", file=sys.stderr)
    return 1


# ──────────────────────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────────────────────
def main() -> int:
    # Checked before the parser is built: the input-topic table names the
    # generated classes, so without them even --help would raise.
    if not HAVE_SYNAPSE_FBS:
        return _die("synapse-fbs is required: pip install synapse-fbs\n"
                    "       (the schema bindings from github.com/CogniPilot/synapse_fbs)")

    parser = argparse.ArgumentParser(
        description=__doc__.splitlines()[3],
        formatter_class=argparse.RawDescriptionHelpFormatter)

    parser.add_argument("--topic", default="external_pose", choices=sorted(input_topics()),
                        help="synapse catalog key to subscribe to (default: external_pose)")
    parser.add_argument("--namespace", default="**",
                        help="zenoh key namespace, e.g. cub1; default ** matches any")
    parser.add_argument("--key", default=None,
                        help="full key expression, overriding --namespace/--topic")
    parser.add_argument("--instance", type=int, default=None,
                        help="ExternalOdometryData.id, or the mocap rigid-body id")
    parser.add_argument("--connect", default=None,
                        help="zenoh router endpoint, e.g. tcp/192.168.1.10:7447")
    parser.add_argument("--mode", default=None, choices=("peer", "client"),
                        help="default: client when --connect is given, else peer")
    parser.add_argument("--no-covariance", dest="covariance", action="store_false",
                        help="ignore external_pose_cov and use --hacc/--vacc instead")
    parser.add_argument("--ignore-flags", action="store_true",
                        help="accept samples whose validity bits are clear, for producers "
                             "that fill the fields but never set the bitmask")

    parser.add_argument("--port", default="/dev/ttyUSB0", help="serial device (default: %(default)s)")
    parser.add_argument("--baud", type=int, default=57600, help="default: 57600 (SiK default)")
    parser.add_argument("--rate", type=float, default=10.0, help="Hz sent to the vehicle")
    parser.add_argument("--dry-run", action="store_true", help="decode and print, no serial port")
    parser.add_argument("--timeout", type=float, default=0.5,
                        help="seconds before a sample counts as stale (default: %(default)s)")

    parser.add_argument("--origin-lat", type=float, default=40.41545396897393)
    parser.add_argument("--origin-lon", type=float, default=-86.93275866259437)
    parser.add_argument("--origin-alt", type=float, default=0.0)
    parser.add_argument("--yaw-offset", type=float, default=230.0,
                        help="degrees the facility X axis is rotated from true north")
    parser.add_argument("--heading-offset", type=float, default=138.0)
    parser.add_argument("--publish-yaw", action="store_true",
                        help="set YawValid and send the attitude yaw")
    parser.add_argument("--hacc", type=float, default=0.05,
                        help="horizontal accuracy in metres when no covariance is available")
    parser.add_argument("--vacc", type=float, default=0.08)
    parser.add_argument("--degraded-scale", type=float, default=4.0,
                        help="accuracy multiplier while the producer reports degraded tracking")
    parser.add_argument("--hdop", type=float, default=0.3)
    parser.add_argument("--vdop", type=float, default=0.4)
    parser.add_argument("--satellites", type=int, default=14)
    parser.add_argument("--gnss-instance", type=int, default=0, help="GnssFixData.id")

    parser.add_argument("--simulate", action="store_true",
                        help="generate a circular trajectory instead of subscribing")
    parser.add_argument("--sim-radius", type=float, default=4.0, help="metres")
    parser.add_argument("--sim-period", type=float, default=20.0, help="seconds per lap")

    parser.add_argument("--selftest", action="store_true", help="check decoding and conversion")
    parser.add_argument("--list-topics", action="store_true", help="show the input topics")

    args = parser.parse_args()

    if args.selftest:
        return cmd_selftest()
    if args.list_topics:
        return cmd_list_topics()

    if topic_catalog.SCHEMA_SET_HASH != FIRMWARE_SCHEMA_SET_HASH:
        return _die(
            f"synapse-fbs schema set {topic_catalog.SCHEMA_SET_HASH} does not match the "
            f"{FIRMWARE_SCHEMA_SET_HASH} the firmware was built against.\n"
            "       Payload layouts may differ; the vehicle would report this as a "
            "climbing bad_len counter.")

    if args.simulate and args.topic != "external_pose":
        return _die("--simulate produces ExternalOdometryData, so it needs "
                    "--topic external_pose")

    return run(args)


if __name__ == "__main__":
    sys.exit(main())
